myEcommernce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mysite.urls',namespace="mysiteUrls")),
    # path('dashboard/', include('dashboard.urls', namespace="dashboardUrls")),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

mysite/urls.py
# writing our urls
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "mysiteUrls"



urlpatterns = [
  path('', views.IndexView.as_view(), name='indexPage'),
  path('login/',views.LoginView.as_view(), name='loginPage'),
  path('signup/',views.SignupView.as_view(), name='signupPage'),
  path('forget_password/', views.Forget_PasswordView.as_view(), name='forget_passwordPage'),
  path('shop/', views.ShopView.as_view(), name='shopPage'),
  path('orders/', views.OrdersView.as_view(), name='ordersPage'),
  path('product_detail/', views.ProductDetailView.as_view(), name='productDetailPage'),
  path('contact/', views.ContactView.as_view(), name='contactPage'),
  path('cart/', views.CartView.as_view(), name='cartPage'),
  path('confirmation/', views.ConfirmationView.as_view(), name='confirmationPage'),
  path('checkout/', views.CheckoutView.as_view(), name='checkoutPage'),



 
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns = format_suffix_patterns(urlpatterns)

mysite/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class LoginView(TemplateView):
    template_name = 'login.html'
    
   

class SignupView(TemplateView):
    template_name = 'signup.html'


class Forget_PasswordView(TemplateView):
    template_name = 'forget_password.html'


class IndexView(TemplateView):
    template_name = 'index.html'
   
    def post(self,request):
        if request.method == 'POST':
            return render(request, 'index.html')
    def get(self,request):
        context = {
            'Home':'active',
            'Shop':'',
            'Orders':'',
            'Contact':'',
        }
        return render(request, 'index.html',context)
        

class ShopView(TemplateView):
    template_name = 'shop.html'

    def get(self, request):
        context = {
            'Home': '',
            'Shop': 'active',
            'Orders': '',
            'Contact': '',
        }
        return render(request, 'shop.html', context)
    

class OrdersView(TemplateView):
    template_name = 'orders.html'

    def get(self, request):
        context = {
            'Home': '',
            'Shop': '',
            'Orders': 'active',
            'Contact': '',
        }
        return render(request, 'orders.html', context)
   
class ProductDetailView(TemplateView):
    template_name = 'product_detail.html'
    def get(self, request):
        context = {
        'Home': '',
            'Shop': 'active',
        'Orders': '',
        'Contact': '',
    }
        return render(request, 'product_detail.html', context)

class ContactView(TemplateView):
    template_name = 'contact.html'
    def get(self, request):
        context = {
        'Home': '',
        'Shop': '',
        'Orders': '',
            'Contact': 'active',
    }
        return render(request, 'contact.html', context)

class CartView(TemplateView):
    template_name = 'cart.html'

    def get(self, request):
        context = {
            'Home': '',
            'Shop': 'active',
            'Orders': '',
            'Contact': '',
        }
        return render(request, 'cart.html', context)

class ConfirmationView(TemplateView):
    template_name = 'confirmation.html'
    def get(self, request):
        context = {
            'Home': '',
            'Shop': '',
            'Orders': 'active',
            'Contact': '',
        }
        return render(request, 'confirmation.html', context)

class CheckoutView(TemplateView):
    template_name = 'checkout.html'

    def get(self, request):
        context = {
            'Home': '',
            'Shop': 'active',
            'Orders': '',
            'Contact': '',
        }
        return render(request, 'checkout.html', context)

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <title>ecommernce</title>
</head>

<body>
{% block content %}
{% endblock %}
</body>
<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

</html>

mysite/templates/cart.html
{% extends 'nav.html' %}
{% load static %}
{% block content %}
<!--start main-->
<div class="col-sm-12 mainbody">
    <!--start shopcontainer-->
    <div class="shopcontainer">
        <h1>shopping cart</h1>
        <p>manage your cart</p>
    </div>
    <!--end shopcontainer-->
   <!-- start cartbody -->
   <div class="col-sm-10 cartbody">
   <!-- start cartcontent -->
   <div class="col-sm-12 cartcontent">
    <!-- start group -->
    <div class = "col-sm-12  cartgroup">
    <!-- start cartcontent1 -->
    <div class="col-sm-6 cartcontent1">
        <h5>product</h5>
    </div>
    <!-- end cartcontent1 -->
    <!-- start cartcontent2 -->
    <div class="col-sm-6  cartcontent2">
        <!-- start cartitem -->
        <div class="col-sm-4">
        <h5>price</h5>
        </div>
        <!-- end cartitem -->
        <!-- start cartitem -->
        <div class="col-sm-4">
            <h5>quantity</h5>
        </div>
        <!-- end cartitem -->
        <!-- start cartitem -->
        <div class="col-sm-4">
            <h5>total</h5>
        </div>
        <!-- end cartitem -->
    </div>
    <!-- end cartcontent2 -->
    </div>
    <!-- end group -->
    <!-- start group -->
    <div class="col-sm-12  cartgroup">
        <!-- start cartcontent1 -->
        <div class="col-sm-6 cartcontent1">
            <div class="col-sm-3 cartitemimg">
<img src="{% static 'img/products/71D9ImsvEtL._UY500_.jpg' %}" height="100%" width="100%"
    alt="logo" />
            </div>
        <p>nike airforce</p>
        </div>
        <!-- end cartcontent1 -->
        <!-- start cartcontent2 -->
        <div class="col-sm-6  cartcontent2">
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <p>ghc 130.00</p>
            </div>
            <!-- end cartitem -->
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
               <div class="cartcount">
        <input type="text" name="count" id="count" value="1">
<div class="cartbtn">
    <button>+</button>
    <button>-</button>

</div>
               </div>
            </div>
            <!-- end cartitem -->
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <p>ghc 520.00</p>
            </div>
            <!-- end cartitem -->
        </div>
        <!-- end cartcontent2 -->
    </div>
    <!-- end group -->
    <!-- start group -->
    <div class="col-sm-12  cartgroup">
        <!-- start cartcontent1 -->
        <div class="col-sm-6 cartcontent1">
            <div class="col-sm-3 cartitemimg">
                <img src="{% static 'img/products/IWC_Portugieser_YC_Moon-Tides_slider_600FI-340x340.jpg' %}" height="100%" width="100%"
                    alt="logo" />
            </div>
            <p>nike airforce</p>
        </div>
        <!-- end cartcontent1 -->
        <!-- start cartcontent2 -->
        <div class="col-sm-6  cartcontent2">
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <p>ghc 130.00</p>
            </div>
            <!-- end cartitem -->
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <div class=" cartcount">
                    <input type="text" name="count" id="count" value="3">
                    <div class="cartbtn">
                        <button>+</button>
                        <button>-</button>
    
                    </div>
                </div>
            </div>
            <!-- end cartitem -->
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <p>ghc 520.00</p>
            </div>
            <!-- end cartitem -->
        </div>
        <!-- end cartcontent2 -->
    </div>
    <!-- end group -->
    <!-- start group -->
    <div class="col-sm-12  cartgroup">
        <!-- start cartcontent1 -->
        <div class="col-sm-6 cartcontent1">
            <div class="col-sm-3 cartitemimg">
                <img src="{% static 'img/products/3170e623-ab80-4678-9628-14cb6033ab171650883660619USPoloAssnMenWhiteClarkinSneakers1.webp' %}" height="100%" width="100%"
                    alt="logo" />
            </div>
            <p>nike airforce</p>
        </div>
        <!-- end cartcontent1 -->
        <!-- start cartcontent2 -->
        <div class="col-sm-6  cartcontent2">
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <p>ghc 130.00</p>
            </div>
            <!-- end cartitem -->
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <div class=" cartcount">
                    <input type="text" name="count" id="count" value="2">
                    <div class="cartbtn">
                        <button>+</button>
                        <button>-</button>
    
                    </div>
                </div>
            </div>
            <!-- end cartitem -->
            <!-- start cartitem -->
            <div class="col-sm-4 pi">
                <p>ghc 520.00</p>
            </div>
            <!-- end cartitem -->
        </div>
        <!-- end cartcontent2 -->
    </div>
    <!-- end group -->
    
   </div>
   <!-- end cartcontent -->
   <!-- start cartupdate -->
   <div class="col-sm-12 cartupdate">
    <a href="">update cart</a>
   </div>
   <!-- end cartupdate -->
    <!-- start cartsubtotal -->
    <div class="col-sm-12 cartsubtotal">
        <!-- start subtotal -->
        <div class="col-sm-6 subtotal">
<p>subtotal</p>
<p>ghc 2100.00</p>

        </div>

<!-- endsubtotal -->
    </div>
    <!-- end cartsubtotal -->
    <!-- start cartsubtotal -->
    <div class="col-sm-12 cartsubtotal">
        <!-- start subtotal -->
        <div class="col-sm-6 subtotal">
            <p>delivery:</p>
            <div class="col-sm-9 delivery">
            <p>fee : ghc 22.00</p>
            <input type="text" name="city" placeholder="Please enter your city">
            <input type="text" name="location" placeholder="Please enter your location">
            <input type="text" name="address" placeholder="please enter your postal address">
        <a href="">save</a>   
        </div>
    
        </div>
    
        <!-- endsubtotal -->
    </div>
    <!-- end cartsubtotal -->
    <!-- start cartupdate -->
    <div class="col-sm-12 cartlast">
        <a href="{% url 'mysiteUrls:shopPage' %}">continue shopping</a>
        <a href="{% url 'mysiteUrls:checkoutPage' %}"> proceed to checkout</a>
    </div>
    <!-- end cartupdate -->
    
   </div>
   <!-- end cartbody--> 
</div>
<!--end main-->

{% endblock %}

mysite/templates/forget_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="logincontainer">

<div class="box">
    <div class="form">
        <div class="row">
            <!--right-->
            <div class="loginright col-sm-6">

                <div class="imgcont col-sm-10">
                    <img src="{% static 'img/undraw_forgot_password_re_hxwm.svg' %}" alt="pic">
                </div>
                <div class="col-sm-10">
                    <p>Have fun exploring the many options available in
                        our online shop. With affordable prices and the latest
                        goodies.
                    </p>
                </div>
                <a href="{% url 'mysiteUrls:signupPage' %}"> Create an Account</a>
            </div>
            <!--right-->

            <!--left-->
            <div class="loginleft col-sm-6">
                <div class="logincontainer col-sm-11">
                    <h2>Forgot your password</h2>
                    <form method="" action="{% url 'mysiteUrls:signupPage' %}">
                        {% csrf_token %}
                        <input type="email" name="email" placeholder="Email">
                        <input type="submit" name="login" value="Send Activation Link">

                    </form>
                </div>
            </div>
            <!--left-->
        </div>
    </div>
</div>
</div>
{% endblock %}

mysite/templates/index.html
{% extends 'nav.html' %}
{% load static %}
{% block content %}
        <!--start main-->
        <div class="col-sm-12 mainbody">
<div class="row">
    <div class="col-sm-4 mainright"></div>
    <div class="col-sm-8 mainleft"></div>
    <!--absolute-->
<div class="mainabsolute col-sm-10">
<div class="row absoluterow">
    <div class="col-sm-4 absoluteright">
    <img src="{% static 'img/stock-photo-shopping-cart-presents-shopping-bags.jpeg' %}" height="90%" width="100%" alt="logo">

    </div>
    <div class="col-sm-8 absoluteleft">
        <h3>have fun while you shop</h3>
        <h1>explore all our products</h1>
        <div class="col-sm-8 textleft ">
<p>Us which over of signs divide dominion deep fill
    bring they're meat beho upon own earth without morning
    over third. Their male dry. They are great appear whose
    land fly grass.</p>
        </div>

<a href="{% url 'mysiteUrls:shopPage' %}" class="explore">explore</a>
    </div>
</div>
</div>
    
    <!--end absolute-->



<!--start after-->
<div class="col-sm-12 itemwrapper ">
    <div class="row ">
        <!--start box-->
        <div class="col-sm-4 itemafter">
            <div class = "col-sm-12 itemafterimg">
    <img src="{% static 'img/products/10741489.jpg' %}" height="100%" width="100%"  alt="logo">
        </div>
<div class="itemaftersub">
    <h6>nike air force</h6>
    <p>shoes category</p>
</div>
            
        </div>
        <!--end box-->
        <!--start box-->
        <div class="col-sm-4 itemafter">
            <div class="col-sm-12 itemafterimg">
<img src="{% static 'img//products/299-2994689_nike-sb-pique-polo-high-resolution-black-t.png' %}" height="100%" width="100%" alt="logo">        
    </div>
            <div class="itemaftersub">
                <h6>nike air force</h6>
                <p>shoes category</p>
            </div>
        
        </div>
        <!--end box-->
        <!--start box-->
        <div class="col-sm-4 itemafter">
            <div class="col-sm-12 itemafterimg">
                <img src="{% static 'img//products/71372c3c3e5b485836902b098f4dbfb4522ac1bb133332f5242fb97dc84cdf24.webp' %}"
                 height="100%" width="100%"    alt="logo">
            </div>
            <div class="itemaftersub">
                <h6>nike air force</h6>
                <p>shoes category</p>
            </div>
        
        </div>
        <!--end box--> 
       
    </div>
</div>
<!--end after-->
<!---->
<div class="col-sm-10 productlist">
<!--start producttext-->
<div class="col-sm-12 producttext">
<p>popular items in the market</p>
<h2>trending products</h2>
</div>
<!--end producttext-->
<!--start itembucket-->
<div class="col-sm-12 itembucket">
<div class="row itembucketrow">
    <!--start itemlist-->
    <div class="col-sm-3 itemlist">
        <div class=" col-sm-12 imgitem">
<img src="{% static 'img/products/Adidas_Yeezy_Boost_350_V2_Blue_Tint_Grey_Three_High_Resolution_Red_B37571_P2.jpg' %}"
  height="100%" width="100%"  alt="logo"/>
        </div>
        <p>clothing</p>
        <h5>hoodie</h5>
        <p>ghc 150.00</p>
   
    </div>
    <!--end itemlist-->
    

    <!--start itemlist-->
    <div class="col-sm-3">
        <div class="col-sm-12 itemlist">
            <div class="imgitem">
                <img src="{% static 'img/products/best-men-watches-samsung-galaxy-watch-3-review-luxe-digital@2x.jpg' %}"
                    alt="logo" />
            </div>
            <p>clothing</p>
            <h5>hoodie</h5>
            <p>ghc 150.00</p>
        </div>
    </div>
    <!--end itemlist-->


    <!--start itemlist-->
    <div class="col-sm-3">
        <div class="col-sm-12 itemlist">
            <div class="imgitem">
                <img src="{% static 'img/products/bleu-de-chanel-parfum-spray-3-4fl-oz-packshot-default-107180-8821897232414.jpg' %}"
                    alt="logo" />
                
            </div>
            <p>clothing</p>
            <h5>hoodie</h5>
            <p>ghc 150.00</p>
        </div>
    </div>
    <!--end itemlist-->


    <!--start itemlist-->
    <div class="col-sm-3">
        <div class="col-sm-12 itemlist">
            <div class="imgitem">
                <img src="{% static 'img/products/istockphoto-172417586-170667a.jpg' %}"
                    alt="logo" />
                
            </div>
            <p>clothing</p>
            <h5>hoodie</h5>
            <p>ghc 150.00</p>
        </div>
    </div>
    <!--end itemlist-->
</div>
</div>
<!--end itembucket-->
</div>
<!--10-->


<!--start discount-->
<div class="col-sm-12 discount ">
    <!--discount sbub-->
    <div class="col-sm-12 discountsub">
            <img src="{% static 'img/products/parallax-bg.png.webp' %}" 
                alt="logo">
<div class="discountlist">
<h1>up to 50% off on all first purchases</h1>
<h3>rush hour</h3>
<p>come get discounts on all first purchases.</p>
<a href="{% url 'mysiteUrls:shopPage' %}" class="explore"> shop now</a>
</div>
<!---->
    </div>
        <!--discount sbub-->
</div>
<!--end discount-->

</div>
</div>
<!--end main-->

{% endblock %}

mysite/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="logincontainer">
<div class="box">
    <div class="form">
        <div class="row">
            <!--right-->
            <div class="loginright col-sm-6">

                <div class="imgcont col-sm-10">
                    <img src="{% static 'img/undraw_explore_re_8l4v.svg' %}" alt="pic">
                </div>
                <div class="col-sm-10">
                    <p>Have fun exploring the many options available in
                        our online shop. With affordable prices and the latest
                        goodies.
                    </p>
                </div>
                <a href="{% url 'mysiteUrls:signupPage' %}"> Create an Account</a>
            </div>
            <!--right-->

            <!--left-->
            <div class="loginleft col-sm-6">
                <div class="logincontainer col-sm-11">
                    <h2>log in to your account</h2>
                    <form method="POST" action="{% url 'mysiteUrls:indexPage' %}">
                        {% csrf_token %}
                        <input type="text" name="username" placeholder="Username" required>
                        <input type="password" name="password" placeholder="Password" required>
                        <input type="submit" name="login" value="Log in">
                        <div class="row space">
                            <a href="{% url 'mysiteUrls:signupPage' %}">Don't have an account?</a>
                            <a href="{% url 'mysiteUrls:forget_passwordPage' %}">forget password?</a>
                        </div>


                    </form>
                </div>
            </div>
            <!--left-->
        </div>
    </div>
</div>

</div>

{% endblock %}

mysite/templates/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <title>ecommernce</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {% comment %} <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> {% endcomment %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <!--start nav-->
        <nav class="navbar navbar-expand-lg navbar-light ">
            <div class="container-fluid">
                <a href="#" class="navbar-brand col-sm-2">  
            <img src="{% static 'img/logo.png' %}" height="35" alt="logo">
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                   <img src="{% static 'img/Menu_52px.png' %}" height="20" alt="logo">
                </a>
                </button>
                <div class="collapse navbar-collapse " id="navbarCollapse">
                    <div class="navbar-nav">
        <a href="{% url 'mysiteUrls:indexPage' %}" class="nav-item nav-link {{Home}}">Home </a>
                        <a href="{% url 'mysiteUrls:shopPage' %}" class="nav-item nav-link {{Shop}} " >Shop</a>
                        <a href="{% url 'mysiteUrls:ordersPage' %}" class="nav-item nav-link {{Orders}}">Orders</a>
                        <a href="{% url 'mysiteUrls:contactPage' %}" class="nav-item nav-link {{Contact}} " >Contact</a>
                            
                
                    </div>
                    <div class="navbar-nav ms-auto " >
                        <div class="count">
                <a href="{% url 'mysiteUrls:cartPage' %}">
            <img src="{% static 'img/shopping_cart_32px.png' %}" height="28" alt="logo">
            </a>
<!-- start count absolute -->
            <div class="countabsolute">
    <input type="text" name="quantity" value="0" id="countabsoluteinput">
</div>
<!-- end count absolute -->
                        </div>
        
                    </div>
            <a href="{% url 'mysiteUrls:loginPage' %}" class="nav-item nav-link log">Login</a>

                </div>
            </div>
        </nav>
        <!--end nav-->


{% block content%}
{% endblock %}







<!--start footer-->
<footer>
<!--start footertop-->
<div class="footertop">
    <div class="footertopitem"></div>
    <!--start footersub-->
    <div class="footersub">
        <div class="footersub1"></div>
        <!--start footersub2-->
        <div class="footersub2">
            <div class="col-sm-10 row">
                <div class="col-sm-5 footersub2mission">
                    <div class="col-sm-8">
<div class="myalign">
    <h2>our mission</h2>
</div>
<p>We are an ecommernce company aimed at helping
    our customers have the best experience with online
    shopping.
</p>
<p>We provide a user friendly interface which assist
customers in locating their products</p>
<p>Powered by UnityElites</p>
                    </div>
                

                </div>
                <!---->
                <div class="col-sm-3 footersub2links">
                    <div class="myalign"><h6>quick links</h6></div>
                <a href="{% url 'mysiteUrls:indexPage' %}" >Home </a>
                <a href="{% url 'mysiteUrls:shopPage' %}" >Shop</a>
                <a href="{% url 'mysiteUrls:ordersPage' %}">orders</a>
                <a href="{% url 'mysiteUrls:contactPage' %}">contact</a>

                    
                </div>
                <!---->
                <div class="col-sm-4 footersub2contact">
                    <div class="myalign">
                        <h6>contact us</h6>
                    </div>
                    <!---->
                   <div class="row remove">
                    <div class="col-sm-1 remove rdb">
                        <img src="{% static 'img/Location_48px.png' %}" height="40%" width="100%" alt="logo">
                    </div>
                    <div class="col-sm-8 rab">
                        <h6>head office</h6>
                        <p>P.O Box 3018 North Legon</p>
                    </div>

                   </div>
                   <!---->
                    <!---->
                    <div class="row remove">
                        <div class="col-sm-1 remove rdb">
                            <img src="{% static 'img/phone_48px.png' %}" height="30%" width="100%" alt="logo">
                        </div>
                        <div class="col-sm-8 rab">
                            <h6>phone number</h6>
                            <p class="rmargin">+233 29972827</p>
                            <p >+233 501283417</p>

                        </div>
                    
                    </div>
                    <!---->
                    <!---->
                    <div class="row remove">
                        <div class="col-sm-1 remove rdb">
                            <img src="{% static 'img/Open email_48px.png' %}" height="30%" width="100%" alt="logo">
                        </div>
                        <div class="col-sm-8 rab ">
                            <h6>email</h6>
                            <p class="rmargin">ecommernce@gmail.com</p>
                            <p>myecommernce@gmail.com</p>

                        </div>
                    
                    </div>
                    <!---->
                    
                </div>



            </div>
        </div>

        <!--end footersub2-->
    </div>
        <!--end footersub-->

    <div class="col-sm-10 footerabsolute">
        <h2>get updated from anywhere </h2>
        <p>register with your email and get news
            about the latest products
        </p>
        <div class="col-sm-6 emailbox">
        <input type="text" class="col-sm-8" placeholder="enter your email...">
        <a href="" class=" subbutton">subscribe </a>    
</div>
    </div>
</div>
<!--end footertop-->


</footer>
<!--end footer-->

</body>
<script src="{% static 'js/main.js' %}"></script>
<!-- MDB -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.js"></script>
</html>

mysite/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="logincontainer">

<div class="box2">
    <div class="form">
        <div class="row">
            <!--right-->
            <div class="loginright col-sm-6">

                <div class="imgcont col-sm-10">
                    <img src="{% static 'img/undraw_walk_dreaming_u-58-a.svg' %}" alt="pic">
                </div>
                <div class="col-sm-10">
                    <p>Create your ecommernce account and start exploring all our amazing product. Your 
                        account details will be needed to log in.
                    </p>
                </div>


                <a href="{% url 'mysiteUrls:loginPage' %}"> Get Started</a>
            </div>
            <!--right-->

            <!--left-->
            <div class="loginleft col-sm-6">
                <div class="logincontainer col-sm-11">
                    <h2>Register for an account</h2>
                    <form action="{% url 'mysiteUrls:loginPage' %}">
                        <input type="text" name="username" placeholder="Username">
                        <input type="email" name="email" placeholder="Email Adress">
                        <input type="password" name="password" placeholder="Password">
                        <input type="password" name="password" placeholder="Confirm Password">

                        <input type="submit" name="login" value="Register">
                        <div class="row space">
                            <a href="{% url 'mysiteUrls:loginPage' %}">Already have an account?</a>
                            <a href="{% url 'mysiteUrls:forget_passwordPage' %}">forget password?</a>
                        </div>


                    </form>
                </div>
            </div>
            <!--left-->
        </div>
    </div>
</div>
</div>
{% endblock %}